<a href="https://colab.research.google.com/github/emankhalid019/exploratory-data-analysis/blob/main/Day01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exploratory Data Analysis (EDA)

In [ ]:
# What is EDA?

# EDA stands for Exploratory Data Analysis.

# In simple words: EDA is the step where we look closely at our data before doing anything else with it.
# We check what the data looks like, find missing values, spot weird/unusual entries, and understand the patterns hiding inside the dataset.

# Think of it like this: before cooking a meal, you first check what ingredients you have, whether anything is missing, and whether anything looks off. EDA is that "checking" step for data.

# In short: EDA = Look at the data -> Understand it -> Clean it -> Get it ready for the next step (modeling).

## Step 0: Install Required Libraries

In [1]:
%pip install matplotlib

Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

In [2]:
%pip install seaborn

Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /usr/local/lib/python3.12/dist-packages (from seaborn) (2.0.2)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.12/dist-packages (from seaborn) (2.2.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /usr/local/lib/python3.12/dist-packages (from seaborn) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->seaborn) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

In [3]:
%pip install numpy

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [4]:
%pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

**The EDA Roadmap**

1. Import Libraries

In [6]:
# Bringing in the tools we need

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
## Our first job as data explorers -> just LOOK at the data carefully before touching anything

 2. Load the Dataset

In [7]:
## Loading the data
## We are using the built-in "titanic" dataset that comes with seaborn
df = sns.load_dataset("titanic")
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

 3. Get the Bigger Picture of the Data

       A)Check the Datatypes

In [8]:
# Step one of understanding data: know what TYPE each column is

df.dtypes

# What the output means:

## int64    -> whole numbers
## float    -> numbers with decimals
## str/object -> text / category-type values
## category -> a fixed set of labels, like First/Second/Third class
## bool     -> True or False values

survived          int64
pclass            int64
sex              object
age             float64
sibsp             int64
parch             int64
fare            float64
embarked         object
class          category
who              object
adult_male         bool
deck           category
embark_town      object
alive            object
alone              bool
dtype: object

        B)Check General Info

In [9]:
df.info()

## This single command tells us a LOT:
## - Total rows -> RangeIndex: 891 entries
## - How many values are actually filled in per column (Non-Null Count)
## - The datatype of every column

## age -> only 714 filled out of 891 -> 177 values missing
## deck -> only 203 filled out of 891 -> 688 values missing

## So checking for missing data is one of the very first things we do in EDA

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

         C)Count the Missing Values

In [10]:
df.isnull().sum()  # counts how many blanks (NaN) each column has

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:
# df2 = df   (kept as a placeholder / scratch cell, not used right now)

            D)Make Sense of the Missing Data (Percentages)

In [11]:
## Missing values as a percentage of the whole column
df.isnull().sum() * 100 / len(df)

# missing_percentage = df.isnull().mean() * 100   # a shortcut way to get the same result

# A common rule of thumb in data science:
## If a column is missing more than ~70-75% of its values, it usually adds little value,so most of the time we simply drop it. (This is a general guideline, not a strict law -it always depends on the situation.)

## Example here -> "deck" is missing about 77% of its data -> a strong candidate to drop.

## For columns missing only a handful of values (like "embarked" and "embark_town" here,missing under 1%), it's usually safer to just drop those few ROWS instead of the whole column,
## since so little data is affected.

## For "age", about 20% of the values are missing. For numeric columns like this, we usually FILL IN (impute) the missing values rather than throwing away the column or the rows -
## common choices are the mean, median, or a value estimated from related columns.

## As a rough guide: once missing data climbs toward 30-40%, imputation becomes worth Considering seriously (again, situation-dependent).

survived        0.000000
pclass          0.000000
sex             0.000000
age            19.865320
sibsp           0.000000
parch           0.000000
fare            0.000000
embarked        0.224467
class           0.000000
who             0.000000
adult_male      0.000000
deck           77.216611
embark_town     0.224467
alive           0.000000
alone           0.000000
dtype: float64

4. Handling Missing Values in EDA

In [ ]:
## How do we actually deal with missing values? It depends on the column type.

## Categorical / Text Data
# Option 1: Fill with the Mode (the most common value) -> usually the safest choice
# Option 2: Fill with a placeholder like "Unknown"
# Option 3: Forward Fill (carry the previous value down)
# Option 4: Backward Fill (carry the next value up)

## Numeric Data (int, float)
# Option 1: Fill with the Mean -> works well when data is roughly symmetric
# Option 2: Fill with the Median -> better when data is skewed / has extreme values
# Option 3: Fill with a fixed constant
# Option 4: Interpolation (estimate based on neighboring values)

## Boolean Data
# Option 1: Fill with the Mode
# Option 2: Fill with False
# Option 3: Fill with True

### NaN simply means "Not a Number" -> it's how pandas marks a missing value

## Why the mean for numeric columns? Because it keeps the filled value within a sensible range
## instead of introducing something way outside the normal spread of the data.

In [12]:
print(df['age'].max())
print(df['age'].min())   # note: if you skip the word print, only the LAST value shows up, not both

80.0
0.42

In [13]:
print(df['age'].mean())

29.69911764705882

In [14]:
df['age'].unique()   # every distinct age value present in the column

array([22.  , 38.  , 26.  , 35.  ,   nan, 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  , 28.  ,
        8.  , 19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  ,
       49.  , 29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  ,
       71.  , 37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 ,
       51.  , 55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  ,
       45.5 , 20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  ,
       60.  , 10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  ,
       70.  , 24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

    A) Fill the Missing Ages with the Mean

In [15]:
## Approach 1: replace every missing age with the average age

df2 = df['age'].fillna(df['age'].mean())
df2

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: age, Length: 891, dtype: float64

In [16]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [17]:
df['age'].fillna(df['age'].mean(), inplace=True)
# Note: this exact syntax is now discouraged in newer pandas versions it still updates the age column, adding inplace=True changes the original dataset directly

/tmp/ipykernel_7395/1368851296.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].mean(), inplace=True)

In [18]:
df.fillna({"age": df["age"].mean()}, inplace=True)  # this is the recommended syntax to use instead

In [19]:
df2 = df

In [20]:
df2.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [21]:
df2.isnull().sum() * 100 / len(df2)

survived        0.000000
pclass          0.000000
sex             0.000000
age             0.000000
sibsp           0.000000
parch           0.000000
fare            0.000000
embarked        0.224467
class           0.000000
who             0.000000
adult_male      0.000000
deck           77.216611
embark_town     0.224467
alive           0.000000
alone           0.000000
dtype: float64

In [22]:
print(df2['age'].min())
print(df2['age'].max())
print(df2['age'].mean())

0.42
80.0
29.69911764705882

In [23]:
df2['age'].unique()

array([22.        , 38.        , 26.        , 35.        , 29.69911765,
       54.        ,  2.        , 27.        , 14.        ,  4.        ,
       58.        , 20.        , 39.        , 55.        , 31.        ,
       34.        , 15.        , 28.        ,  8.        , 19.        ,
       40.        , 66.        , 42.        , 21.        , 18.        ,
        3.        ,  7.        , 49.        , 29.        , 65.        ,
       28.5       ,  5.        , 11.        , 45.        , 17.        ,
       32.        , 16.        , 25.        ,  0.83      , 30.        ,
       33.        , 23.        , 24.        , 46.        , 59.        ,
       71.        , 37.        , 47.        , 14.5       , 70.5       ,
       32.5       , 12.        ,  9.        , 36.5       , 51.        ,
       55.5       , 40.5       , 44.        ,  1.        , 61.        ,
       56.        , 50.        , 36.        , 45.5       , 20.5       ,
       62.        , 41.        , 52.        , 63.        , 23.5       ,
        0.92      , 43.        , 60.        , 10.        , 64.        ,
       13.        , 48.        ,  0.75      , 53.        , 57.        ,
       80.        , 70.        , 24.5       ,  6.        ,  0.67      ,
       30.5       ,  0.42      , 34.5       , 74.        ])

In [24]:
df2.fillna({"age": df2["age"].mean()}, inplace=True)

In [25]:
df3 = df2

In [26]:
df3.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

   B) Drop a Column Entirely

In [27]:
## "deck" has way too many missing values (about 77%), so we drop the whole column

df3 = df3.drop(columns=["deck"])

In [28]:
df3

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.000000,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.000000,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.000000,0,0,8.0500,S,Third,man,True,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,Second,man,True,Southampton,no,True
887,1,1,female,19.000000,0,0,30.0000,S,First,woman,False,Southampton,yes,True
888,0,3,female,29.699118,1,2,23.4500,S,Third,woman,False,Southampton,no,False
889,1,1,male,26.000000,0,0,30.0000,C,First,man,True,Cherbourg,yes,True
890,0,3,male,32.000000,0,0,7.7500,Q,Third,man,True,Queenstown,no,True

In [29]:
df3.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       2
class          0
who            0
adult_male     0
embark_town    2
alive          0
alone          0
dtype: int64

In [30]:
df4 = df3

   C)Fill in the Remaining Missing Values

In [31]:
## "embark_town" and "embarked" are text/category columns, so we fill their few gaps with the Mode

df4.fillna({"embark_town": df4["embark_town"].mode()[0]}, inplace=True)
df4.fillna({"embarked": df4["embarked"].mode()[0]}, inplace=True)

In [32]:
df4.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

**Quick Refresher: Mean, Median, Modet**

In [ ]:
## Mean, Median, Mode - explained simply

# Mean: the average value. Add every number together, then divide by how many numbers there are.

# Median: the middle value once the numbers are sorted smallest to largest.
# Example: 4, 6, 9, 12 -> the two middle numbers are 6 and 9 -> median = (6+9)/2 = 7.5

# Mode: the value that shows up most often in the data.
# Example: 4, 6, 8, 8, 8, 10, 12, 10 -> mode = 8 (appears three times, more than any other value)
# If there's a tie, there can be more than one mode - mode()[0] simply grabs the first one.

**What is Data Wrangling?**

In [ ]:
# Data Wrangling (also called data munging) is the process of taking raw, messy data and reshaping it into a clean, structured, ready-to-use format.

## EDA and Data Wrangling usually happen side by side, not one strictly after the other.

 EDA vs. Wrangling - What's the Difference?

In [ ]:
## Exploring the data (EDA) means figuring out what's WRONG or missing in it.

## Wrangling means actually FIXING those problems.

# EDA            = "What's going on with my data?"
# Data Wrangling  = "How do I fix it?"



## EDA (Explore)              Data Wrangling (Fix)
# Spot the problem              Solve the problem
# Count missing values          Fill in / drop missing values
# Check for duplicates          Remove duplicates
# Detect outliers               Treat / remove outliers
# Understand the data           Prepare the data for modeling

In [33]:
print("mean = ", df["age"].mean())
print("median = ", df["age"].median())
print("mode = ", df["age"].mode())

## mean and median end up close to each other here

mean =  29.69911764705882
median =  29.69911764705882
mode =  0    29.699118
Name: age, dtype: float64

In [34]:
print("mode =", df["embark_town"].mode())

mode = 0    Southampton
Name: embark_town, dtype: object

In [35]:
print("mode =", df["embarked"].mode())

mode = 0    S
Name: embarked, dtype: object

In [ ]:
## Two big skills we're practicing here:

# 1. How to explore data
# 2. How to fix / handle what we find

In [ ]:
df
# Each row = one passenger's record
# e.g. row 0 -> did not survive, 3rd class, male, age 22, travelling with 1 sibling/spouse,paid a fare of 7.25, boarded at Southampton, travelling alone = False

Understanding Every Variable

In [ ]:
## There are 14 variables (columns) in total in our cleaned data.
## Suppose one of them still has gaps - we can often estimate (impute) those missing values
## by looking at the OTHER variables and how they relate to each other.

## When we use the relationships between variables to fill in missing values,
## that itself is a small example of a machine learning approach to imputation.

## Data Wrangling - The Full Roadmap

In [ ]:
## Data Wrangling Roadmap

# 1. Import Libraries

# 2. Import the Dataset

# 3. Explore the data
# ->  1. Info (df.info())
# ->  2. Datatypes
# ->  3. Missing Values
# ->  4. Get a general feel for the data

# 4. Understand every variable

# 5. Study relationships between variables (Heatmap, Pairplot, Correlation)

# 6. Decide the next move
# ->  1. Normalize -> bring values onto a similar scale so they can be fairly compared
# ->  2. Handle Outliers -> deal with values that don't seem to belong with the rest

# 7. End up with tidy, clean data
####  We usually spend about 80% of project time here

# 8. Ready for Statistical Analysis
# 9. Ready for Prediction
# 10. Ready for Machine Learning
# 11. Ready for Deep Learning
#### Only about 20% of project time goes here

**A Common Rule in Data Science**

In [ ]:
## Rule of thumb in the data science world:
## Out of 100 hours spent on a data project, expect roughly 80 hours to go into cleaning and wrangling the data before any modeling even starts.

**Normalization Techniques (Quick List)**

In [ ]:
## Normalization Techniques

# 1. Min-Max Scaling
# 2. Standardization (Z-Score Scaling)
# 3. Robust Scaling
# 4. Max Absolute Scaling
# 5. Unit Vector Scaling (L1 / L2 Normalization)

**Outlier Detection & Handling (Quick List)**

In [ ]:
## Ways to SPOT Outliers

# 1. Box Plot
# 2. Scatter Plot
# 3. Histogram
# 4. IQR (Interquartile Range) Method -> most commonly used
# 5. Z-Score Method
# 6. Modified Z-Score
# 7. Percentile Method
# 8. Isolation Forest (Machine Learning)
# 9. Local Outlier Factor - LOF (Machine Learning)
# 10. DBSCAN (Clustering-based)


## Ways to HANDLE Outliers

# 1. Remove them -> simply delete the rows containing outliers
# 2. Capping / Winsorization -> cap extreme values at an upper/lower limit instead of deleting
# 3. Transform the data
#    ->  Log Transformation
#    ->  Square Root Transformation
#    ->  Box-Cox Transformation
#    ->  Yeo-Johnson Transformation
# 4. Replace with Mean/Median -> swap extreme values instead of removing them outright
# 5. Use Robust Models -> pick algorithms that are naturally less sensitive to outliers(e.g., tree-based models like Decision Trees / Random Forest)